<html>
<head>
	<title>РЭУ Кемеровский институт</title>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
	<META name="Author" content="http://ailus.ru"><meta name="Copyright" content="http://ailus.ru">	
</head>

<body leftmargin="0" topmargin="0" marginwidht="0" margimheihgt="0" rightmargin="0" bottommargin="0" bgcolor="#3366ff">
<link href="index/css" type="text/css" rel="STYLESHEET">

<table border=1 width=100% height=20%>

<td width=100% height=20% align=center> Лабораторные работы по курсу "Динамические веб-системы в экономике" <br> Студента группы ПИ-163: Обухова Владислава Константиновича <br> Проверил к.т.к доц. Назимов А.С.
</td>

</table>


<table border=1 width=100% height=70%>

<td width=30% height=70% align=left>

<a href="orderform.php"> Первая лабораторная работа </a>
<br><br>
<a href="orderform_2.php"> Вторая лабораторная работа </a>
<br><br>
<a href=""> Третья лабораторная работа </a>
<br><br>
<a href=""> Четвертая лабораторная работа </a>
<br><br>
<a href=""> Пятая лабораторная работа </a>

</td>
<td width=70% height=70% align=center>
</html>